// <auto-generated />
using System;
using FirstWebMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstWebMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230726060150_Create_Table_Faculty")]
    partial class Create_Table_Faculty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("FirstWebMVC.Models.Animal", b =>
                {
                    b.Property<string>("GiongLoai")
                        .HasColumnType("TEXT");

                    b.Property<string>("TuoiTho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("XuatXu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GiongLoai");

                    b.ToTable("Animal");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FirstWebMVC.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Faculty", b =>
                {
                    b.Property<string>("FacultyID")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FacultyID");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SinhNhat")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Cat", b =>
                {
                    b.HasBaseType("FirstWebMVC.Models.Animal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Cat");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Dog", b =>
                {
                    b.HasBaseType("FirstWebMVC.Models.Animal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Dog");
                });

            modelBuilder.Entity("FirstWebMVC.Models.Cat", b =>
                {
                    b.HasOne("FirstWebMVC.Models.Animal", null)
                        .WithOne()
                        .HasForeignKey("FirstWebMVC.Models.Cat", "GiongLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FirstWebMVC.Models.Dog", b =>
                {
                    b.HasOne("FirstWebMVC.Models.Animal", null)
                        .WithOne()
                        .HasForeignKey("FirstWebMVC.Models.Dog", "GiongLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
